### ISSUE TITLE
Enabling several keypairs to be generated (i.e count > 1)

### ISSUE THREAD

**Issue by muranant** [terraform-aws-modules/terraform-aws-key-pair#14]
We recently found a need to create a keypair with every VM that we create. So there were two updates to the module.
One was to support count in this module and use this array of keys in the VM module.

```
resource "aws_key_pair" "this" {
  count      = var.key_count
  key_name   = var.key_count == 1 ? var.key_name : format("%s-%03d", var.key_name, (count.index + 1))
  public_key = var.ssh_public_key
  tags = var.tags
}


```
I can create a PR for the same, if you feel there is a need to entertain it.

**Comment by antonbabenko** [comment]
Hi @muranant !

There is no need to use `count` inside of the module because you can call this module multiple time to get several resources created, like described here:
* https://learn.hashicorp.com/tutorials/terraform/for-each?in=terraform/0-13&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS
* https://www.terraform.io/docs/language/meta-arguments/for_each.html

```terraform
module "key_pair" {
  for_each   = toset(["key1", "key2"])

  source     = "terraform-aws-modules/key-pair/aws"
  key_name   = each.key
}
```
